Fix: _get_args_from_config
Summary:
Hi,

For the following code snippet:

```
from detectron2.config import CfgNode, configurable

def from_config_func(a):
    return {}

configurable(from_config=from_config_func)
def func():
    pass

func(CfgNode())
```

It will raise following error:

```AttributeError: 'function' object has no attribute '__self__'```

Which is not worked as our expected.

That we need to identify the `from_config_func` is a `function` or a `method`.

Pull Request resolved: https://github.com/facebookresearch/detectron2/pull/2375

Reviewed By: theschnitz

Differential Revision: D25492901

Pulled By: ppwwyyxx

fbshipit-source-id: db88a9e52596bba76240242db639b7933b1a9a6d