Fix densepose dumping
Summary:
Adds extra arg to fix densepose dumping. [This commit](https://github.com/ilyakava/detectron2/commit/4566e02ed773dbb9bc4d84ca7b04e675bd1a79c9) forgot to update the second definition of `create_context` when changing how the class method was used.

When this script is run in dump mode you will get the error:
```
[01/12 21:50:26 apply_net]: Loading config from ../../../third_party/github/detectron2/configs/COCO-Keypoints/ke
ypoint_rcnn_R_50_FPN_1x.yaml
[01/12 21:50:26 apply_net]: Loading model from ../../../models/third_party/detectron2/coco/model_final_04e291.pk
l
[01/12 21:50:27 apply_net]: Loading data from /examples/small_folder
Traceback (most recent call last):
  File "../../../third_party/github/detectron2/projects/DensePose/apply_net.py", line 345, in <module>
    main()
  File "../../../third_party/github/detectron2/projects/DensePose/apply_net.py", line 341, in main
    args.func(args)
  File "../../../third_party/github/detectron2/projects/DensePose/apply_net.py", line 95, in execute
    context = cls.create_context(args, cfg)
TypeError: create_context() takes 2 positional arguments but 3 were given
```

Pull Request resolved: https://github.com/facebookresearch/detectron2/pull/2481

Reviewed By: MarcSzafraniec

Differential Revision: D25917686

Pulled By: vkhalidov

fbshipit-source-id: d62f6833ab0a679e2269f85e2676cd5283c862a9